version: 0.0
os: linux
files:
 - source: /
   destination: /home/ubuntu/urban-potato
   
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  ApplicationStart:
   - location: scripts/update_app
     timeout: 300
     runas: root
